spring:
  application:
    name: see-freemarker
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.246.57:3306/Seddb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useInformationSchema=true&nullNamePatternMatchesAll=true
    username: yjbuser
    password: YunJianBiao@)18
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://127.0.0.1:9014/seddb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useInformationSchema=true&nullNamePatternMatchesAll=true
    #    username: user_eqodsflse801s8sjc
    #    password: a_gtuT5Z8C
    type: com.zaxxer.hikari.HikariDataSource
logging:
  level:
    com:
      soeasyeasy: debug
server:
  servlet:
    context-path: /code
  port: 8080
