# 例如在 dev1.yml 中
server:
  port: 9000
  netty:
    max-initial-line-length: 32KB
logging:
  level:
    com.soeasyeasy: debug
    org.springframework.cloud.gateway: debug
    reactor.netty.http.client: info

spring:
  application:
    name: see-gateway
  profiles:
    active: dev
  cloud:
    gateway:
      default-filters:
      routes:
        - id: see-system
          uri: http://localhost:8081
          predicates:
            - Path=/system/**
        - id: see-ai
          uri: http://localhost:8082
          predicates:
            - Path=/ai/**
        - id: see-auth
          uri: http://localhost:9001
          predicates:
            - Path=/auth/**
        - id: see-freemarker
          uri: http://localhost:8080
          predicates:
            - Path=/code/**



